module.exports = {
    reforges: {
        perfect: 'diamond_atom',
        spiked: 'dragon_scale',
        fabled: 'dragon_claw',
        renowned: 'dragon_horn',
        cubic: 'molten_cube',
        reinforced: 'rare_diamond',
        magnetic: 'lapis_crystal',
        gilded: 'midas_jewel',
        fruitful: 'onyx',
        precise: 'optical_lens',
        ridiculous: 'red_nose',
        loving: 'red_scarf',
        suspicious: 'suspicious_vial',
        spiritual: 'spirit_stone',
        warped: 'warped_stone',
        shaded: 'dark_orb',
        giant: 'giant_tooth',
        empowered: 'sadans_brooch',
        moil: 'moil_log',
        dirty: 'dirt_bottle',
        toil: 'toil_log',
        refined: 'refined_amber',
        blessed: 'blessed_fruit',
        candied: 'candy_corn',
        sweet: 'rock_candy',
        submerged: 'deep_sea_orb',
        ancient: 'precursor_gear',
        withered: 'wither_blood',
        aote_stone: 'aote_stone',
        ambered: 'amber_material',
        jaded: 'jaderald',
        auspicious: 'rock_gemstone',
        fleet: 'diamonite',
    },
    all_reforges: [
        'gentle',
        'odd',
        'fast',
        'fair',
        'epic',
        'sharp',
        'heroic',
        'spicy',
        'legendary',
        'dirty',
        'fabled',
        'suspicious',
        'gilded',
        'warped',
        'withered',
        'bulky',
        "jerry's",
        'salty',
        'treacherous',
        'stiff',
        'lucky',
        'deadly',
        'fine',
        'grand',
        'hasty',
        'neat',
        'rapid',
        'unreal',
        'awkward',
        'rich',
        'precise',
        'spiritual',
        'headstrong',
        'clean',
        'fierce',
        'heavy',
        'light',
        'mythic',
        'pure',
        'smart',
        'titanic',
        'wise',
        'very',
        'highly',
        'extremely',
        'not so',
        'thicc',
        'absolutely',
        'undead',
        'perfect',
        'necrotic',
        'ancient',
        'spiked',
        'renowned',
        'cubic',
        'warped',
        'reinforced',
        'loving',
        'ridiculous',
        'giant',
        'submerged',
        'empowered',
        'candied',
        'jaded',
        'bizarre',
        'itchy',
        'ominous',
        'pleasant',
        'pretty',
        'shiny',
        'simple',
        'strange',
        'vivid',
        'godly',
        'demonic',
        'forceful',
        'hurtful',
        'keen',
        'strong',
        'superior',
        'unpleasant',
        'zealous',
        'silky',
        'bloody',
        'shaded',
        'sweet',
        'even more',
        'fruitful',
        'magnetic',
        'refined',
        'blessed',
        'moil',
        'toil',
        'fleet',
        'stellar',
        'mithraic',
        'auspicious',
        'bountiful',
        'ambered',
        'double_bit',
        'green_thumb',
        'unyielding',
        'lumberjack',
        'peasant',
        'prospector',
        'great',
        'rugged',
        'lush',
        'robust',
        'zooming',
        'excellent',
        'sturdy',
        'fortunate',
    ],
};
